/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gambar = new javax.swing.JLabel();
        welcome1 = new javax.swing.JLabel();
        welcome2 = new javax.swing.JLabel();
        bt_barang = new javax.swing.JButton();
        bt_transaksi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bt_pelanggan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N
        jPanel1.add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 360, 130));

        welcome1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        welcome1.setForeground(new java.awt.Color(0, 102, 102));
        welcome1.setText("Selamat Datang di Toko Online");
        jPanel1.add(welcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, -1));

        welcome2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        welcome2.setForeground(new java.awt.Color(0, 102, 102));
        welcome2.setText("ALFARO");
        jPanel1.add(welcome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, 20));

        bt_barang.setText("Barang");
        bt_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_barangActionPerformed(evt);
            }
        });
        jPanel1.add(bt_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        bt_transaksi.setText("Transaksi");
        bt_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_transaksiActionPerformed(evt);
            }
        });
        jPanel1.add(bt_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jButton1.setText("Exit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        bt_pelanggan.setText("Pelanggan");
        bt_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pelangganActionPerformed(evt);
            }
        });
        jPanel1.add(bt_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pelangganActionPerformed
        // TODO add your handling code here:
        new pelanggan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_pelangganActionPerformed

    private void bt_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_barangActionPerformed
        // TODO add your handling code here:
        new barang().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_barangActionPerformed

    private void bt_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_transaksiActionPerformed
        // TODO add your handling code here:
        new transaksi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_transaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_barang;
    private javax.swing.JButton bt_pelanggan;
    private javax.swing.JButton bt_transaksi;
    private javax.swing.JLabel gambar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel welcome1;
    private javax.swing.JLabel welcome2;
    // End of variables declaration//GEN-END:variables
}
